export const didNumberMockState =
{
    items: [
        {
            i_did_number: 1111,
            area_name: 'Not Applicable',
            country_name: 'Not Applicable',
            did_number: '000000001111',
            description: '',
            is_provisioned: 0,
            i_customer: 88,
            pricing: {
                customer_costs: {
                    activation: 0,
                    periodic: 0,
                    free_of_charge: 'N',
                    iso_4217: 'USD',
                },
            },
        },
        {
            i_did_number: 1112,
            area_name: null,
            country_name: null,
            did_number: '000000001113',
            description: '',
            is_provisioned: 0,
            i_customer: 99,
            pricing: {
                customer_costs: {
                    activation: 1.0,
                    periodic: 10,
                    free_of_charge: 'N',
                    iso_4217: 'USD',
                },
            },
        },
        {
            i_did_number: 1113,
            area_name: null,
            country_name: 'United States of America',
            did_number: '12060261240',
            extension_id: '4001',
            master_account_id: '11165400001',
            description: '',
            i_account: 1141944,
            extension_name: 'Fake User',
            i_master_account: 6666666,
            is_provisioned: 0,
            i_customer: 11,
            pricing: {
                customer_costs: {
                    activation: 0,
                    periodic: 0,
                    free_of_charge: 'N',
                    iso_4217: 'USD',
                },
            },
        },
    ],
        total: 3,
    filters: {},
    loading: false,
        accountsToAssign: { isLoading: false },
}

export const noDidStoreDataMock = {
    items: null,
    total: 0,
    loading: false,
    filters: { offset: 0 },
    accountsToAssign: {
        isLoading: false,
        items: [
            {
                redirect_number: '222222',
                time_zone_name: 'zone name',
                i_prompt: null,
                product_visible_name: 'BE_Product_010',
                out_date_format: 'YYYY-MM-DD',
                email: 'one@email.com',
                password: 'zzzqqq123',
                blocked: 'N',
                bill_status: 'O',
                life_time: undefined,
                ua_profile_id: 32,
                login: 'asdasd',
                i_role: 6,
                in_date_format: 'YYYY-MM-DD',
                phone1: '',
                i_time_zone: 297,
                phone2: '',
                salutation: '',
                assigned_addons: [],
                billing_model: 1,
                extension_name: 'Sebastian',
                country: 'PL',
                i_batch: 52,
                i_account_role: 1,
                included_services: [],
                inactivity_expire_time: undefined,
                product_name: 'BE_Product_010',
                activation_date: new Date('2009-09-18'),
                firstname: '',
                i_product: 12,
                extension_id: '4001',
                iso_4217: 'USD',
                iso_639_1: 'en',
                batch_name: 'BE_Batch_1001',
                state: 'Mazowieckie',
                i_account: 450055,
                opening_balance: 0,
                id: '11165400001',
                out_date_time_format: 'YYYY-MM-DD HH24:MI:SS',
                subscriber_email: '',
                last_usage: new Date('2011-04-11 14:46:05'),
                h323_password: '123test',
                i_lang: 'en',
                idle_days: 3668,
                zip: '1234',
                balance: 4.23189,
                midinit: '',
                cont1: '',
                lastname: '',
                city: 'Sample',
                out_time_format: 'HH24:MI:SS',
                cont2: '',
                service_features: [],
                ecommerce_enabled: 'N',
                first_usage_time: new Date('2009-09-28 02:00:00'),
                in_time_format: 'HH24:MI:SS',
                expiration_date: new Date('2023-01-13'),
                service_flags: 'NY^^~NNY7^YN~Y~ N^~Y   N',
                note: '',
                sip_status: 0,
                issue_date: new Date('2009-09-18'),
                faxnum: '',
                control_number: 1,
                i_acl: 155,
                i_customer: 19,
                baddr1: '123 Green. Str.',
                companyname: '',
                credit_limit: undefined,
            },
            {
                i_prompt: null,
                time_zone_name: 'time_zone',
                redirect_number: '888888',
                state: 'some state',
                zip: 'some sip',
                i_master_account: 15,
                baddr1: 'dr',
                city: 'city',
                country: 'country',
                i_product: 12,
                activation_date: new Date('2009-09-18'),
                product_visible_name: 'BE_Product_010',
                extension_id: '4002',
                iso_639_1: 'en',
                iso_4217: 'USD',
                batch_name: 'BE_Batch_1001',
                out_date_format: 'YYYY-MM-DD',
                i_account: 450056,
                email: 'two@email.com',
                opening_balance: 0,
                password: 'mjkcqq1u',
                blocked: 'N',
                id: '11165400002',
                out_date_time_format: 'YYYY-MM-DD HH24:MI:SS',
                last_usage: new Date('2011-04-11 14:46:05'),
                h323_password: '6v5tb1',
                bill_status: 'O',
                i_lang: 'en',
                life_time: undefined,
                login: '11165400002',
                i_role: 6,
                idle_days: 3668,
                balance: 2.07533,
                in_date_format: 'YYYY-MM-DD',
                i_time_zone: 113,
                assigned_addons: [],
                billing_model: 1,
                extension_name: 'Anna',
                out_time_format: 'HH24:MI:SS',
                service_features: [],
                ecommerce_enabled: 'N',
                i_account_role: 1,
                i_batch: 52,
                in_time_format: 'HH24:MI:SS',
                first_usage_time: new Date('2009-09-26 02:00:00'),
                expiration_date: new Date('2023-01-13'),
                service_flags: ' ^^^~NNY ^YN~ ~ N',
                sip_status: 0,
                included_services: [],
                issue_date: new Date('2009-09-18'),
                control_number: 2,
                i_customer: 19,
                i_acl: 155,
                inactivity_expire_time: undefined,
                credit_limit: undefined,
                product_name: 'BE_Product_010',
            },
        ],
        total: 2,
    },
}
